# Use an official lightweight Python image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file first to leverage Docker cache
COPY requirements.txt .

# Install dependencies (ignoring warnings for a cleaner build log)
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project codebase into the container
COPY . .

# Set the default command (we will override this with Airflow later)
CMD ["python", "main.py"]